In [146]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Normalizer

In [8]:
%pwd

'/Users/hpitawela'

In [40]:
# Reading files and populate dataframes
df_matrix = pd.read_csv('/Users/hpitawela/uiowa/LDA/link.csv', delimiter=",")

In [41]:
df_matrix.shape

(46155, 3)

In [42]:
df_matrix.head()

ID                                           FROM_URL  \
0   1                                  https://uiowa.edu   
1   2  https://admissions.uiowa.edu/apply/apply?utm_s...   
2   3                               http://www.uiowa.edu   
3   4                               http://www.uiowa.edu   
4   5                   https://iam.uiowa.edu/whitepages   

                                              TO_URL  
0  https://admissions.uiowa.edu/apply/apply?utm_s...  
1                               http://www.uiowa.edu  
2  https://admissions.uiowa.edu/apply/apply?utm_s...  
3                   https://iam.uiowa.edu/whitepages  
4                     https://www.uiowa.edu/students

In [43]:
df_matrix.insert(3, 'Value', 1)

In [44]:
df_matrix.head()

ID                                           FROM_URL  \
0   1                                  https://uiowa.edu   
1   2  https://admissions.uiowa.edu/apply/apply?utm_s...   
2   3                               http://www.uiowa.edu   
3   4                               http://www.uiowa.edu   
4   5                   https://iam.uiowa.edu/whitepages   

                                              TO_URL  Value  
0  https://admissions.uiowa.edu/apply/apply?utm_s...      1  
1                               http://www.uiowa.edu      1  
2  https://admissions.uiowa.edu/apply/apply?utm_s...      1  
3                   https://iam.uiowa.edu/whitepages      1  
4                     https://www.uiowa.edu/students      1

In [45]:
# Deleting duplicate From_url, To_url rows
df_A = df_matrix.drop_duplicates(subset=['FROM_URL','TO_URL'], keep='first', inplace=False)
df_A.shape

(44184, 4)

In [91]:
# In order to align rows and columns I am using 2 dataframes, one with From_url as column headers and 
# another with To_url as column_headers
# Later I am aligning columns in each other filling missing columns with zeros.
df_matrix_A = df_A.pivot(index='FROM_URL',columns='TO_URL',values='Value')
df_matrix_B = df_A.pivot(index='TO_URL',columns='FROM_URL',values='Value')

In [92]:
df_matrix_A.shape

(6719, 7349)

In [93]:
df_matrix_B.shape

(7349, 6719)

In [49]:
df_matrix_A.head()

TO_URL                                              http%3A/recserv.uiowa.edu  \
FROM_URL                                                                        
http://admissions.uiowa.edu                                               NaN   
http://admissions.uiowa.edu/                                              NaN   
http://admissions.uiowa.edu/academics                                     NaN   
http://admissions.uiowa.edu/academics/undergrad...                        NaN   
http://admissions.uiowa.edu/contact-us                                    NaN   

TO_URL                                              http://Miriam-thaggert@uiowa.edu  \
FROM_URL                                                                               
http://admissions.uiowa.edu                                                      NaN   
http://admissions.uiowa.edu/                                                     NaN   
http://admissions.uiowa.edu/academics                                            NaN   
http://admissions.uiowa.edu/academics/undergrad...                               NaN   
http://admissions.uiowa.edu/contact-us                                           NaN   

TO_URL                                              http://admissions.uiowa.edu  \
FROM_URL                                                                          
http://admissions.uiowa.edu                                                 NaN   
http://admissions.uiowa.edu/                                                NaN   
http://admissions.uiowa.edu/academics                                       NaN   
http://admissions.uiowa.edu/academics/undergrad...                          NaN   
http://admissions.uiowa.edu/contact-us                                      NaN   

TO_URL                                              http://admissions.uiowa.edu/  \
FROM_URL                                                                           
http://admissions.uiowa.edu                                                  NaN   
http://admissions.uiowa.edu/                                                 NaN   
http://admissions.uiowa.edu/academics                                        NaN   
http://admissions.uiowa.edu/academics/undergrad...                           NaN   
http://admissions.uiowa.edu/contact-us                                       NaN   

TO_URL                                              http://admissions.uiowa.edu/academics  \
FROM_URL                                                                                    
http://admissions.uiowa.edu                                                           NaN   
http://admissions.uiowa.edu/                                                          NaN   
http://admissions.uiowa.edu/academics                                                 NaN   
http://admissions.uiowa.edu/academics/undergrad...                                    NaN   
http://admissions.uiowa.edu/contact-us                                                NaN   

TO_URL                                              http://admissions.uiowa.edu/academics/undergraduate-areas-of-study  \
FROM_URL                                                                                                                 
http://admissions.uiowa.edu                                                                       NaN                    
http://admissions.uiowa.edu/                                                                      NaN                    
http://admissions.uiowa.edu/academics                                                             NaN                    
http://admissions.uiowa.edu/academics/undergrad...                                                NaN                    
http://admissions.uiowa.edu/contact-us                                                            NaN                    

TO_URL                                              http://admissions.uiowa.edu/contact-us  \
FROM_URL                                   

In [71]:
df_A['FROM_URL'].values

array(['https://uiowa.edu',
       'https://admissions.uiowa.edu/apply/apply?utm_source=uiowa&utm_campaign=homepage_header',
       'http://www.uiowa.edu', ...,
       'https://web.archive.org/web/20050508013844/http://www.uiowa.edu:80/homepage/directories/index.html',
       'https://web.archive.org/web/20050508013844/http://www.uiowa.edu:80/homepage/directories/index.html',
       'https://web.archive.org/web/20050508013844/http://www.uiowa.edu:80/homepage/directories/index.html'],
      dtype=object)

In [72]:
df_A['TO_URL'].values

array(['https://admissions.uiowa.edu/apply/apply?utm_source=uiowa&utm_campaign=homepage_header',
       'http://www.uiowa.edu',
       'https://admissions.uiowa.edu/apply/apply?utm_source=uiowa&utm_campaign=homepage_header',
       ...,
       'https://web.archive.org/web/20010701140950/http://www.uiowa.edu:80/homepage/directories/index.html',
       'https://web.archive.org/web/20060516010900/http://www.uiowa.edu/homepage/directories/index.html',
       'https://web.archive.org/web/20050508013844/http://www.uiowa.edu/'],
      dtype=object)

In [75]:
missing_from_urls = set(df_A['TO_URL'].values) - set(df_A['FROM_URL'].values)

In [80]:
len(missing_from_urls)

630

In [81]:
missing_to_urls = set(df_A['FROM_URL'].values) - set(df_A['TO_URL'].values)

In [82]:
len(missing_to_urls)

0

In [161]:
# Aligining columns of matrix A with matrix B
df_matrix_A_aligned, df_matrix_B_aligned = df_matrix_A.align(df_matrix_B, axis=0, fill_value=0)

In [162]:
# Now we have a square matrix for A
df_matrix_A_aligned.shape

(7349, 7349)

In [163]:
# We no longer need B
df_matrix_B_aligned.shape

(7349, 6719)

In [104]:
list(missing_from_urls)

['http://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fuiowa.edu%2Fstories%2Fstudent-outcomes&title=Student%20Outcomes',
 'http://feedproxy.google.com/~r/lyndacom-new-releases/~3/yNVhwKO_kOA/714290-2.html?org=uiowa.edu',
 'http://hris.uiowa.edu/classcomp/merit/descr_docs/GA66.doc',
 'http://classrooms.uiowa.edu/classrooms.aspx?room=SC-3026',
 'http://hris.uiowa.edu/classcomp/merit/descr_docs/GJ14.doc',
 'http://hris.uiowa.edu/classcomp/merit/descr_docs/GG93.doc',
 'http://hris.uiowa.edu/classcomp/merit/descr_docs/GA48.doc',
 'https://web.archive.org/web/20080604120510/http://www.uiowa.edu:80/homepage/hub/tours.html/',
 'http://fyi.uiowa.edu/wp-content/uploads/2012/02/460-MATHESON-120127-TS-35.jpg',
 'https://veterans.org.uiowa.edu/node/471/edit',
 'http://purl.lib.uiowa.edu/gale/bncn',
 'http://www.uiowa.edu/%7Ebiocat/contact_map_driving.html',
 'https://isis.uiowa.edu/isis2/guest-login.page',
 'http://hris.uiowa.edu/classcomp/merit/descr_docs/GG07.doc',
 'http://hris.uiowa

In [108]:
df_test = df_matrix_A_aligned.loc[list(missing_from_urls)]

In [109]:
df_test.shape

(630, 7349)

In [164]:
pd.unique(df_test[df_test.columns].values.ravel('K'))

array([0.])

In [165]:
test = df_matrix_A_aligned.index == df_matrix_A_aligned.columns

In [166]:
test

array([ True,  True,  True, ...,  True,  True,  True])

In [167]:
pd.unique(test)

array([ True])

In [284]:
df_matrix_A_aligned_without_nan = df_matrix_A_aligned.fillna(0)

In [285]:
df_matrix_A_aligned_without_nan.head()

TO_URL                                 http%3A/recserv.uiowa.edu  \
http%3A/recserv.uiowa.edu                                    0.0   
http://Miriam-thaggert@uiowa.edu                             0.0   
http://admissions.uiowa.edu                                  0.0   
http://admissions.uiowa.edu/                                 0.0   
http://admissions.uiowa.edu/academics                        0.0   

TO_URL                                 http://Miriam-thaggert@uiowa.edu  \
http%3A/recserv.uiowa.edu                                           0.0   
http://Miriam-thaggert@uiowa.edu                                    0.0   
http://admissions.uiowa.edu                                         0.0   
http://admissions.uiowa.edu/                                        0.0   
http://admissions.uiowa.edu/academics                               0.0   

TO_URL                                 http://admissions.uiowa.edu  \
http%3A/recserv.uiowa.edu                                      0.0   
http://Miriam-thaggert@uiowa.edu                               0.0   
http://admissions.uiowa.edu                                    0.0   
http://admissions.uiowa.edu/                                   0.0   
http://admissions.uiowa.edu/academics                          0.0   

TO_URL                                 http://admissions.uiowa.edu/  \
http%3A/recserv.uiowa.edu                                       0.0   
http://Miriam-thaggert@uiowa.edu                                0.0   
http://admissions.uiowa.edu                                     0.0   
http://admissions.uiowa.edu/                                    0.0   
http://admissions.uiowa.edu/academics                           0.0   

TO_URL                                 http://admissions.uiowa.edu/academics  \
http%3A/recserv.uiowa.edu                                                0.0   
http://Miriam-thaggert@uiowa.edu                                         0.0   
http://admissions.uiowa.edu                                              0.0   
http://admissions.uiowa.edu/                                             0.0   
http://admissions.uiowa.edu/academics                                    0.0   

TO_URL                                 http://admissions.uiowa.edu/academics/undergraduate-areas-of-study  \
http%3A/recserv.uiowa.edu                                                            0.0                    
http://Miriam-thaggert@uiowa.edu                                                     0.0                    
http://admissions.uiowa.edu                                                          0.0                    
http://admissions.uiowa.edu/                                                         0.0                    
http://admissions.uiowa.edu/academics                                                0.0                    

TO_URL                                 http://admissions.uiowa.edu/contact-us  \
http%3A/recserv.uiowa.edu                                                 0.0   
http://Miriam-thaggert@uiowa.edu                                          0.0   
http://admissions.uiowa.edu                                               0.0   
http://admissions.uiowa.edu/                                              0.0   
http://admissions.uiowa.edu/academics                                     0.0   

TO_URL                                 http://admissions.uiowa.edu/parents-family/health-insurance-requirement  \
http%3A/recserv.uiowa.edu                                                            0.0                         
http://Miriam-thaggert@uiowa.edu                                                     0.0                         
http://admissions.uiowa.edu                                                          0.0                         
http://admissions.uiowa.edu/                                                         0.0                         
http://admissions.uiowa.edu/academics                                                0.0           

In [286]:
pd.unique(df_matrix_A_aligned_without_nan[df_matrix_A_aligned_without_nan.columns].values.ravel('K'))

array([0., 1.])

In [287]:
df_matrix_A_aligned_without_nan.sum(axis=1)

http%3A/recserv.uiowa.edu                                                                                            0.0
http://Miriam-thaggert@uiowa.edu                                                                                     0.0
http://admissions.uiowa.edu                                                                                          4.0
http://admissions.uiowa.edu/                                                                                         3.0
http://admissions.uiowa.edu/academics                                                                                3.0
http://admissions.uiowa.edu/academics/undergraduate-areas-of-study                                                   3.0
http://admissions.uiowa.edu/contact-us                                                                               4.0
http://admissions.uiowa.edu/parents-family/health-insurance-requirement                                              3.0
http://admissions.uiowa.edu/visi

In [314]:
df_matrix_A_aligned_without_nan.head()

TO_URL                                 http%3A/recserv.uiowa.edu  \
http%3A/recserv.uiowa.edu                                    0.0   
http://Miriam-thaggert@uiowa.edu                             0.0   
http://admissions.uiowa.edu                                  0.0   
http://admissions.uiowa.edu/                                 0.0   
http://admissions.uiowa.edu/academics                        0.0   

TO_URL                                 http://Miriam-thaggert@uiowa.edu  \
http%3A/recserv.uiowa.edu                                           0.0   
http://Miriam-thaggert@uiowa.edu                                    0.0   
http://admissions.uiowa.edu                                         0.0   
http://admissions.uiowa.edu/                                        0.0   
http://admissions.uiowa.edu/academics                               0.0   

TO_URL                                 http://admissions.uiowa.edu  \
http%3A/recserv.uiowa.edu                                      0.0   
http://Miriam-thaggert@uiowa.edu                               0.0   
http://admissions.uiowa.edu                                    0.0   
http://admissions.uiowa.edu/                                   0.0   
http://admissions.uiowa.edu/academics                          0.0   

TO_URL                                 http://admissions.uiowa.edu/  \
http%3A/recserv.uiowa.edu                                       0.0   
http://Miriam-thaggert@uiowa.edu                                0.0   
http://admissions.uiowa.edu                                     0.0   
http://admissions.uiowa.edu/                                    0.0   
http://admissions.uiowa.edu/academics                           0.0   

TO_URL                                 http://admissions.uiowa.edu/academics  \
http%3A/recserv.uiowa.edu                                                0.0   
http://Miriam-thaggert@uiowa.edu                                         0.0   
http://admissions.uiowa.edu                                              0.0   
http://admissions.uiowa.edu/                                             0.0   
http://admissions.uiowa.edu/academics                                    0.0   

TO_URL                                 http://admissions.uiowa.edu/academics/undergraduate-areas-of-study  \
http%3A/recserv.uiowa.edu                                                            0.0                    
http://Miriam-thaggert@uiowa.edu                                                     0.0                    
http://admissions.uiowa.edu                                                          0.0                    
http://admissions.uiowa.edu/                                                         0.0                    
http://admissions.uiowa.edu/academics                                                0.0                    

TO_URL                                 http://admissions.uiowa.edu/contact-us  \
http%3A/recserv.uiowa.edu                                                 0.0   
http://Miriam-thaggert@uiowa.edu                                          0.0   
http://admissions.uiowa.edu                                               0.0   
http://admissions.uiowa.edu/                                              0.0   
http://admissions.uiowa.edu/academics                                     0.0   

TO_URL                                 http://admissions.uiowa.edu/parents-family/health-insurance-requirement  \
http%3A/recserv.uiowa.edu                                                            0.0                         
http://Miriam-thaggert@uiowa.edu                                                     0.0                         
http://admissions.uiowa.edu                                                          0.0                         
http://admissions.uiowa.edu/                                                         0.0                         
http://admissions.uiowa.edu/academics                                                0.0           

In [315]:
pd.unique(df_matrix_A_aligned_without_nan[df_matrix_A_aligned_without_nan.columns].values.ravel('K'))

array([0.        , 0.33333333, 0.2       , 0.16666667, 0.125     ,
       0.25      , 0.08333333, 0.05263158, 0.09090909, 0.06666667,
       0.04761905, 0.0625    , 0.05      , 1.        , 0.07142857,
       0.1       , 0.14285714, 0.11111111, 0.5       , 0.07692308,
       0.05882353, 0.05555556, 0.04      , 0.04545455, 0.04347826,
       0.03846154, 0.04166667, 0.03703704, 0.03225806, 0.03571429,
       0.01785714, 0.01724138, 0.01754386, 0.01694915, 0.01818182,
       0.01923077, 0.01960784, 0.02941176, 0.0212766 , 0.02      ,
       0.01408451, 0.02083333, 0.02857143, 0.03333333, 0.03448276,
       0.02777778, 0.03030303, 0.03125   , 0.02040816, 0.02631579,
       0.02564103, 0.00357143, 0.025     , 0.02702703, 0.02222222,
       0.02272727, 0.00462963, 0.015625  ])

In [301]:
# Normalizing matrix A across rows
df_matrix_A_aligned_without_nan.iloc[:,:] = Normalizer(norm='l1').fit_transform(df_matrix_A_aligned_without_nan)

In [302]:
pd.unique(df_matrix_A_aligned_without_nan[df_matrix_A_aligned_without_nan.columns].values.ravel('K'))

array([0.        , 0.33333333, 0.2       , 0.16666667, 0.125     ,
       0.25      , 0.08333333, 0.05263158, 0.09090909, 0.06666667,
       0.04761905, 0.0625    , 0.05      , 1.        , 0.07142857,
       0.1       , 0.14285714, 0.11111111, 0.5       , 0.07692308,
       0.05882353, 0.05555556, 0.04      , 0.04545455, 0.04347826,
       0.03846154, 0.04166667, 0.03703704, 0.03225806, 0.03571429,
       0.01785714, 0.01724138, 0.01754386, 0.01694915, 0.01818182,
       0.01923077, 0.01960784, 0.02941176, 0.0212766 , 0.02      ,
       0.01408451, 0.02083333, 0.02857143, 0.03333333, 0.03448276,
       0.02777778, 0.03030303, 0.03125   , 0.02040816, 0.02631579,
       0.02564103, 0.00357143, 0.025     , 0.02702703, 0.02222222,
       0.02272727, 0.00462963, 0.015625  ])

In [303]:
a_matrix = df_matrix_A_aligned_without_nan.values

In [304]:
a_matrix

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.01754386, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [124]:
df_matrix_A_aligned_copy = df_matrix_A_aligned

In [129]:
# Max value of each row is saved in a new column max_value
df_matrix_A_aligned_copy['max_value'] = df_matrix_A_aligned_copy.max(axis=1)

In [130]:
df_matrix_A_aligned_copy['max_value']

http%3A/recserv.uiowa.edu                                                                                           0.0
http://Miriam-thaggert@uiowa.edu                                                                                    0.0
http://admissions.uiowa.edu                                                                                         1.0
http://admissions.uiowa.edu/                                                                                        1.0
http://admissions.uiowa.edu/academics                                                                               1.0
http://admissions.uiowa.edu/academics/undergraduate-areas-of-study                                                  1.0
http://admissions.uiowa.edu/contact-us                                                                              1.0
http://admissions.uiowa.edu/parents-family/health-insurance-requirement                                             1.0
http://admissions.uiowa.edu/visit-campus

In [135]:
# index and max_value column are separated into a new dataframe
d_matrix = df_matrix_A_aligned_copy[['max_value']].copy()

In [216]:
# Replace d_matrix values as 0 -> 1 and 1 -> 0
d_matrix_1_replaced = d_matrix.replace(1, -1)
d_matrix_0_replaced = d_matrix_1_replaced.replace(0, 1)
d_matrix_replaced = d_matrix_0_replaced.replace(-1, 0)
d_matrix.shape

(7349, 1)

In [217]:
d_matrix.head()

TO_URL                                 max_value
http%3A/recserv.uiowa.edu                    0.0
http://Miriam-thaggert@uiowa.edu             0.0
http://admissions.uiowa.edu                  1.0
http://admissions.uiowa.edu/                 1.0
http://admissions.uiowa.edu/academics        1.0

In [218]:
d_matrix_replaced.head()

TO_URL                                 max_value
http%3A/recserv.uiowa.edu                    1.0
http://Miriam-thaggert@uiowa.edu             1.0
http://admissions.uiowa.edu                  0.0
http://admissions.uiowa.edu/                 0.0
http://admissions.uiowa.edu/academics        0.0

In [219]:
# Converting d_matrix_replaced to numpy matrix
d_mat = d_matrix_replaced.values

In [220]:
d_mat.shape

(7349, 1)

In [221]:
df_matrix_A_aligned.index

Index(['http%3A/recserv.uiowa.edu', 'http://Miriam-thaggert@uiowa.edu',
       'http://admissions.uiowa.edu', 'http://admissions.uiowa.edu/',
       'http://admissions.uiowa.edu/academics',
       'http://admissions.uiowa.edu/academics/undergraduate-areas-of-study',
       'http://admissions.uiowa.edu/contact-us',
       'http://admissions.uiowa.edu/parents-family/health-insurance-requirement',
       'http://admissions.uiowa.edu/visit-campus/visit-options-first-year-students',
       'http://advisingcenter.uiowa.edu',
       ...
       'https://www.medicine.uiowa.edu/', 'https://www.uiowa.edu',
       'https://www.uiowa.edu/alumni-and-friends',
       'https://www.uiowa.edu/faculty-and-staff',
       'https://www.uiowa.edu/parents', 'https://www.uiowa.edu/students',
       'https://www2.education.uiowa.edu/belinblank/',
       'https://www2.education.uiowa.edu/belinblank/students/bests/#Group46',
       'https://www2.education.uiowa.edu/forms/grsc/',
       'https://www2.education.uio

In [140]:
# Add a new column as prob to get initial probability 1/n
df_matrix_A_aligned_copy['prob'] = 1/7349

In [141]:
df_matrix_A_aligned_copy['prob']

http%3A/recserv.uiowa.edu                                                                                           0.000136
http://Miriam-thaggert@uiowa.edu                                                                                    0.000136
http://admissions.uiowa.edu                                                                                         0.000136
http://admissions.uiowa.edu/                                                                                        0.000136
http://admissions.uiowa.edu/academics                                                                               0.000136
http://admissions.uiowa.edu/academics/undergraduate-areas-of-study                                                  0.000136
http://admissions.uiowa.edu/contact-us                                                                              0.000136
http://admissions.uiowa.edu/parents-family/health-insurance-requirement                                             0.000136


In [142]:
# Separating index and prob columns to a new dataframe
p_matrix = df_matrix_A_aligned_copy[['prob']].copy()

In [144]:
p_matrix.head()

TO_URL                                     prob
http%3A/recserv.uiowa.edu              0.000136
http://Miriam-thaggert@uiowa.edu       0.000136
http://admissions.uiowa.edu            0.000136
http://admissions.uiowa.edu/           0.000136
http://admissions.uiowa.edu/academics  0.000136

In [222]:
# Building p0 matrix from p_matrix dataframe with equal initial probabilities
p_mat = p_matrix.values

In [223]:
p_mat

array([[0.00013607],
       [0.00013607],
       [0.00013607],
       ...,
       [0.00013607],
       [0.00013607],
       [0.00013607]])

In [224]:
# Building e matrix as [1,1,1,......,1] with dimensions 1x7349 
e_matrix = np.ones(7349).reshape([1,7349])

In [225]:
e_matrix

array([[1., 1., 1., ..., 1., 1., 1.]])

In [226]:
e_matrix.shape

(1, 7349)

In [227]:
p0 = p_mat

In [228]:
p0.shape

(7349, 1)

In [307]:
# Running the probability calculation iterations
for i in range(20):
    p1 = np.dot(p0.T, a_matrix)+np.dot(np.dot(p0.T, d_mat), e_matrix/7349)
    p1 = p1/np.linalg.norm(p1)
    p0 = p1.T

In [308]:
p1

array([[3.36608176e-07, 2.13286949e-07, 9.97942808e-07, ...,
        1.90838667e-07, 3.63988681e-07, 1.78725907e-07]])

In [309]:
p0

array([[3.36608176e-07],
       [2.13286949e-07],
       [9.97942808e-07],
       ...,
       [1.90838667e-07],
       [3.63988681e-07],
       [1.78725907e-07]])

In [310]:
# Get dataframe back from final probabilities
df = pd.DataFrame(data=p0,index=df_matrix_A_aligned.index,columns=p_matrix.columns)

In [311]:
df.head()

TO_URL                                         prob
http%3A/recserv.uiowa.edu              3.366082e-07
http://Miriam-thaggert@uiowa.edu       2.132869e-07
http://admissions.uiowa.edu            9.979428e-07
http://admissions.uiowa.edu/           8.270345e-06
http://admissions.uiowa.edu/academics  2.471277e-07

In [312]:
# Sort probabilities to find most important urls ignore TO_URL
df.sort_values(by=['prob'], ascending=False)

TO_URL                                                      prob
https://admissions.uiowa.edu/apply/apply?utm_so...  5.727185e-01
http://www.uiowa.edu                                5.720371e-01
https://iam.uiowa.edu/whitepages                    3.803111e-01
https://www.uiowa.edu/students                      3.795974e-01
https://uiowa.edu                                   1.924865e-01
https://now.uiowa.edu                               9.473181e-02
https://now.uiowa.edu/media-relations               9.394151e-02
https://now.uiowa.edu/staff-list                    3.121132e-02
https://now.uiowa.edu/about                         1.156890e-02
https://now.uiowa.edu/contact                       5.043215e-03
https://uiowa.edu/university-shared-services/ebuy   2.147131e-03
https://uiowa.edu/university-shared-services/ev...  2.147131e-03
https://uiowa.edu/university-shared-services/pu...  2.147131e-03
https://uiowa.edu/university-shared-services/tr...  2.147131e-03
https://uiowa.edu/university-shared-services/ed...  2.147131e-03
https://uiowa.edu/university-shared-services/pr...  2.147131e-03
https://uiowa.edu/university-shared-services/us...  1.822035e-03
https://now.uiowa.edu/submissions                   1.203612e-03
https://ir.uiowa.edu                                1.075806e-03
https://ir.uiowa.edu/do/search/advanced/            1.075255e-03
https://web.archive.org/web/20080330212900/http...  9.072860e-04
https://web.archive.org/web/20080509185840/http...  8.891699e-04
https://web.archive.org/web/19970618091516/http...  8.265185e-04
https://web.archive.org/web/20000511091041/http...  7.239630e-04
https://web.archive.org/web/19971008221618/http...  7.150376e-04
https://web.archive.org/web/19970228213232/http...  6.455004e-04
https://web.archive.org/web/20080701235603/http...  6.338753e-04
https://web.archive.org/web/19970606111314/http...  6.164816e-04
https://web.archive.org/web/20040208004242/http...  5.874312e-04
https://ir.uiowa.edu/communities.html               5.394012e-04
...                                                          ...
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/mer

In [313]:
# Sort probabilities to find least important urls ignore TO_URL
df.sort_values(by=['prob'], ascending=True)

TO_URL                                                      prob
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
http://hris.uiowa.edu/classcomp/merit/descr_doc...  1.676790e-07
...                                                          ...
https://ir.uiowa.edu/communities.html               5.394012e-04
https://web.archive.org/web/20040208004242/http...  5.874312e-04
https://web.archive.org/web/19970606111314/http...  6.164816e-04
https://web.archive.org/web/20080701235603/http...  6.338753e-04
https://web.archive.org/web/19970228213232/http...  6.455004e-04
https://web.archive.org/web/19971008221618/http...  7.150376e-04
https://web.archive.org/web/20000511091041/http...  7.239630e-04
https://web.archive.org/web/19970618091516/http...  8.265185e-04
https://web.archive.org/web/20080509185840/http...  8.891699e-04
https://web.archive.org/web/20080330212900/http...  9.072860e-04
https://ir.uiowa.edu/do/search/advanced/            1.075255e-03
https://ir.uiowa.edu                                1.075806e-03
https://now.uiowa.edu/submissions                   1.203612e-03
https://uiowa.edu/university-shared-services/us...  1.822035e-03
https://uiowa.edu/university-shared-services/tr...  2.147131e-03
https://uiowa.edu/university-shared-services/pu...  2.147131e-03
https://uiowa.edu/university-shared-services/pr...  2.147131e-03
https://uiowa.edu/university-shared-services/ev...  2.147131e-03
https://uiowa.edu/university-shared-services/ed...  2.147131e-03
https://uiowa.edu/university-shared-services/ebuy   2.147131e-03
https://now.uiowa.edu/contact                       5.043215e-03
https://now.uiowa.edu/about                         1.156890e-02
https://now.uiowa.edu/staff-list                    3.121132e-02
https://now.uiowa.edu/media-relations               9.394151e-02
https://now.uiowa.edu                               9.473181e-02
https://uiowa.edu                                   1.924865e-01
https://www.uiowa.edu/students                      3.795974e-01
https://iam.uiowa.edu/whitepages                    3.803111e-01
http://www.uiowa.edu                                5.720371e-01
https://admissions.uiowa.edu/apply/